// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.2.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ÀirportTest.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.2.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("CarParkBooking")]
    public partial class CarParkBookingFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "CarParkBooking.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "CarParkBooking", @"1.	Select Carpark - terminal, date, time, carpark & valet services 
(select an overnight period across two days)
2.	Select Add-ons –  Strata Lounge for one adult
3.	Enter Your Details (for new users on right hand side) - name, address, phone number, 
email address. Please select both checkboxes
4.	Enter Payment Details – please use standard test credit card number (4111111111111111) 
and any name, CVC & expiry date. On this page you will also need to enter vehicle details 
for Valet – i.e. Vehicle make, vehicle colour and registration.
5.	Confirmation page is the last step. (This can take up to 30 seconds to load)
NB - You will also receive a confirmation email which is out of scope.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Book an Overnight CarPark with Strata")]
        [NUnit.Framework.CategoryAttribute("mytag")]
        public virtual void BookAnOvernightCarParkWithStrata()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Book an Overnight CarPark with Strata", new string[] {
                        "mytag"});
#line 15
this.ScenarioSetup(scenarioInfo);
#line 16
 testRunner.Given("I navigate to the Auckland Airport URL \'SelfUrl\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 17
 testRunner.And("I navigate to the Car Park Managment", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 18
 testRunner.And("I select CarPark, Terminal, Date, Time and Valet Services", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 19
 testRunner.And("I select AddOns Strata Lounge for One Adult", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Title",
                        "FirstName",
                        "LastName",
                        "Address",
                        "Phone",
                        "Email"});
            table1.AddRow(new string[] {
                        "Mr",
                        "Santhosh",
                        "Ippili",
                        "168 Parnell Road, Parnell, Auckland, New Zealand",
                        "0223702755",
                        "santhosh.ippili@qualit.co.nz"});
#line 20
 testRunner.When("I enter my personal details for New Users", ((string)(null)), table1, "When ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "CardNumber",
                        "Name",
                        "SecurityCode",
                        "ExpiryMonth",
                        "ExpiryYear",
                        "LicensePlateNo",
                        "CarMAke",
                        "CarColor",
                        "FlightNo"});
            table2.AddRow(new string[] {
                        "4111111111111111",
                        "Santhosh",
                        "123",
                        "12",
                        "2018",
                        "KKB337",
                        "Toyota",
                        "Blue",
                        "Test123"});
#line 23
 testRunner.And("I enter the payment\tdetails", ((string)(null)), table2, "And ");
#line 26
 testRunner.Then("the confirmation page appears", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
